#!/bin/sh

echo "Stopping dbus-ble-sensors-py service"
if [ -n "$(ls /sys/class/bluetooth)" ]; then
    svc -d /service/dbus-ble-sensors-py
    rm -r /service/dbus-ble-sensors-py
fi

echo "Modifying ble services autostart scripts"
sed -i 's|/service/dbus-ble-sensors-py |/service/dbus-ble-sensors |g' /lib/udev/bt-config
sed -i 's|/service/dbus-ble-sensors-py$|/service/dbus-ble-sensors|g' /lib/udev/bt-remove

echo "Starting dbus-ble-sensors service"
if [ -n "$(ls /sys/class/bluetooth)" ]; then
    svc -u /service/dbus-ble-sensors
fi
